# Generated by Django 4.1.7 on 2023-03-28 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_short', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlshort',
            name='original_url',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='urlshort',
            name='short_url',
            field=models.URLField(editable=False),
        ),
    ]
