# Generated by Django 4.1.7 on 2023-03-28 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('url_short', '0002_alter_urlshort_original_url_alter_urlshort_short_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='urlshort',
            old_name='original_url',
            new_name='url',
        ),
    ]
